# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./data_types/Image.h \
    ./data_types/Object.h \
    ./data_types/typized_objects/BiRecognizableObject.h \
    ./data_types/typized_objects/NeighbourRecognizableObject.h \
    ./data_types/typized_objects/PartsRecognizableObject.h \
    ./data_types/typized_objects/SimilarRecognizableObject.h \
    ./simulation/Simulation.h \
    ./interface/AlgorithmResults/AlgorithmResults.h \
    ./interface/DetailedView/DetailedView.h \
    ./interface/MainWindow/MainWindow.h
SOURCES += ./main.cpp \
    ./data_types/Image.cpp \
    ./data_types/Object.cpp \
    ./data_types/typized_objects/BiRecognizableObject.cpp \
    ./data_types/typized_objects/NeighbourRecognizableObject.cpp \
    ./data_types/typized_objects/PartsRecognizableObject.cpp \
    ./data_types/typized_objects/SimilarRecognizableObject.cpp \
    ./interface/AlgorithmResults/AlgorithmResults.cpp \
    ./interface/DetailedView/DetailedView.cpp \
    ./interface/MainWindow/MainWindow.cpp \
    ./simulation/Simulation.cpp
FORMS += ./interface/AlgorithmResults/AlgorithmResults.ui \
    ./interface/DetailedView/DetailedView.ui \
    ./interface/MainWindow/MainWindow.ui
RESOURCES += interface/MainWindow/MainWindow.qrc
